# Generated by Django 5.2 on 2025-04-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnpj", models.CharField(max_length=20, unique=True)),
                ("razao_social", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Etapa",
        ),
    ]
