# Generated by Django 5.2 on 2025-07-28 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_empresa_delete_etapa"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Empresa",
        ),
    ]
